apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: hello
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-helloweb
  annotations:
    kubernetes.io/tls-acme: "true" # enable certificates
    kubernetes.io/ingress.class: "nginx"
  labels:
    app: hello
spec:
  tls: # specify domains to fetch certificates for
  - hosts:
    - hello-world.k8s.n0q.org
    secretName: helloweb-service-tls
  rules:
  - host: hello-world.k8s.n0q.org
    http:
      paths:
      - path: /
        backend:
          serviceName: helloweb
          servicePort: 8080

